/**
 * ===================================================================
 * MAK SRI KITCHEN - MENU DATA
 * 100% Olahan Spesial Ayam Mak Sri Kitchen
 * ===================================================================
 */

const MAK_SRI_CONFIG = {
  "storeName": "Mak Sri Kitchen",
  "tagline": "Ayam Popcorn & Aneka Olahan Ayam Juara",
  "whatsappNumber": "62895703265466",
  "address": "Jl. Veteran, Muja Muju, Kec. Umbulharjo, Kota Yogyakarta, Daerah Istimewa Yogyakarta 55164",
  "operatingHours": "Senin - Minggu: 15:00 - 22:00 WIB",
  "googleMapsUrl": "https://www.google.com/maps/place/Mak+Sri+Kitchen/@-7.8074317,110.3917577,17z/data=!3m1!4b1!4m6!3m5!1s0x2e7a57e0a995bb3b:0x508a72bef1b55946!8m2!3d-7.807437!4d110.3943326!16s%2Fg%2F11nw80yppn?entry=ttu",
  "instagramUrl": "https://www.instagram.com/maksrikitchen"
};

const MENU_ITEMS = [
  {
    "id": "paket-nasi-asam-manis",
    "name": "Nasi + Ayam Asam Manis",
    "category": "paket-nasi",
    "badge": "Paket Nasi",
    "tagClass": "tag-bestseller",
    "spiceLevel": "Asam Manis",
    "price": 18000,
    "soldOut": false,
    "portionTag": "Paket Komplit",
    "desc": "Paket kenyang Nasi putih hangat + Ayam crispy saos asam manis oriental khas Mak Sri.",
    "image": "assets/images/menu-koloke.jpg"
  },
  {
    "id": "paket-nasi-cah-jamur",
    "name": "Nasi + Ayam Cah Jamur",
    "category": "paket-nasi",
    "badge": "Habis",
    "tagClass": "tag-habis",
    "spiceLevel": "Gurih Sedap",
    "price": 0,
    "soldOut": true,
    "portionTag": "",
    "desc": "Paket Nasi hangat + potongan ayam empuk dan aneka jamur tumis gurih.",
    "image": "assets/images/menu-cah-jamur.jpg"
  },
  {
    "id": "paket-nasi-saos-keju",
    "name": "Nasi + Ayam Saos Keju",
    "category": "paket-nasi",
    "badge": "Paket Nasi",
    "tagClass": "tag-gurih",
    "spiceLevel": "Creamy Cheese",
    "price": 18000,
    "soldOut": false,
    "portionTag": "Paket Komplit",
    "desc": "Paket kenyang Nasi putih hangat + Ayam renyah berpadu dengan saos keju creamy gurih spesial.",
    "image": "assets/images/menu-saos-keju.jpg"
  },
  {
    "id": "paket-nasi-lada-garam",
    "name": "Nasi + Ayam Lada Garam",
    "category": "paket-nasi",
    "badge": "Pedas Gurih",
    "tagClass": "tag-pedas",
    "spiceLevel": "Level Pedas Pas",
    "price": 18000,
    "soldOut": false,
    "portionTag": "Paket Komplit",
    "desc": "Paket kenyang Nasi putih hangat + Ayam goreng crispy tumis cabai rawit merah & bawang putih wangi.",
    "image": "assets/images/menu-lada-garam.jpg"
  },
  {
    "id": "paket-nasi-telur-asin",
    "name": "Nasi + Ayam Telur Asin Mak Sri",
    "category": "paket-nasi",
    "badge": "Habis",
    "tagClass": "tag-habis",
    "spiceLevel": "Gurih Creamy",
    "price": 0,
    "soldOut": true,
    "portionTag": "",
    "desc": "Paket Nasi + Ayam saos kuning telur asin asli khas Mak Sri.",
    "image": "assets/images/menu-telur-asin.jpg"
  },
  {
    "id": "paket-nasi-original",
    "name": "Nasi + Ayam Original",
    "category": "paket-nasi",
    "badge": "Extra Crispy",
    "tagClass": "tag-gurih",
    "spiceLevel": "Gurih Renyah",
    "price": 18000,
    "soldOut": false,
    "portionTag": "Paket Komplit",
    "desc": "Paket kenyang Nasi putih hangat + Ayam fillet crispy renyah gurih bumbu rempah.",
    "image": "assets/images/menu-tepung-oat.jpg"
  },
  {
    "id": "paket-nasi-lada-hitam",
    "name": "Nasi + Ayam Lada Hitam",
    "category": "paket-nasi",
    "badge": "Blackpepper",
    "tagClass": "tag-pedas",
    "spiceLevel": "Hangat Pedas",
    "price": 18000,
    "soldOut": false,
    "portionTag": "Paket Komplit",
    "desc": "Paket kenyang Nasi putih hangat + Ayam empuk saus blackpepper pekat sensasi pedas hangat.",
    "image": "assets/images/menu-lada-hitam.jpg"
  },
  {
    "id": "paket-nasi-tahu-tausi",
    "name": "Nasi + Ayam Tahu Tausi",
    "category": "paket-nasi",
    "badge": "Habis",
    "tagClass": "tag-habis",
    "spiceLevel": "Gurih Fermentasi",
    "price": 0,
    "soldOut": true,
    "portionTag": "",
    "desc": "Paket Nasi + Olahan ayam dan tahu sutra lembut bumbu tausi kedelai hitam.",
    "image": "assets/images/menu-tahu-tausi.jpg"
  },
  {
    "id": "lauk-koloke",
    "name": "Ayam Asam Manis",
    "category": "saus",
    "badge": "Porsi Lauk",
    "tagClass": "tag-bestseller",
    "spiceLevel": "Asam Manis",
    "price": 35000,
    "soldOut": false,
    "portionTag": "Porsi 2-4x",
    "desc": "Lauk doang bisa untuk 2-4x makan. Ayam crispy dengan saos asam manis oriental khas Mak Sri Kitchen (saos dibungkus terpisah).",
    "image": "assets/images/menu-koloke.jpg"
  },
  {
    "id": "lauk-cah-jamur",
    "name": "Ayam Cah Jamur",
    "category": "saus",
    "badge": "Habis",
    "tagClass": "tag-habis",
    "spiceLevel": "Gurih Sedap",
    "price": 0,
    "soldOut": true,
    "portionTag": "Porsi 2-4x",
    "desc": "Lauk doang bisa untuk 2-4x makan. Aneka sayur segar, aneka jamur pilihan, dan potongan daging ayam empuk.",
    "image": "assets/images/menu-cah-jamur.jpg"
  },
  {
    "id": "lauk-saos-keju",
    "name": "Ayam Saos Keju",
    "category": "saus",
    "badge": "Porsi Lauk",
    "tagClass": "tag-gurih",
    "spiceLevel": "Creamy Cheese",
    "price": 35000,
    "soldOut": false,
    "portionTag": "Porsi 2-4x",
    "desc": "Lauk doang bisa untuk 2-4x makan. Ayam renyah berpadu dengan cocolan saos keju creamy gurih spesial (saos dibungkus terpisah).",
    "image": "assets/images/menu-saos-keju.jpg"
  },
  {
    "id": "lauk-lada-garam",
    "name": "Ayam Lada Garam",
    "category": "saus",
    "badge": "Porsi Lauk",
    "tagClass": "tag-pedas",
    "spiceLevel": "Level Pedas Pas",
    "price": 35000,
    "soldOut": false,
    "portionTag": "Porsi 2-4x",
    "desc": "Lauk doang bisa untuk 2-4x makan. Ayam goreng crispy renyah ditumis bumbu cabai rawit, bawang putih wangi, dan garam gurih.",
    "image": "assets/images/menu-lada-garam.jpg"
  },
  {
    "id": "lauk-telur-asin",
    "name": "Ayam Telur Asin Mak Sri",
    "category": "saus",
    "badge": "Habis",
    "tagClass": "tag-habis",
    "spiceLevel": "Gurih Creamy",
    "price": 0,
    "soldOut": true,
    "portionTag": "Porsi 2-4x",
    "desc": "Lauk doang bisa untuk 2-4x makan. Diolah dengan baluran saos telur asin (salted egg) asli racikan rahasia Mak Sri Kitchen.",
    "image": "assets/images/menu-telur-asin.jpg"
  },
  {
    "id": "lauk-original",
    "name": "Ayam Original",
    "category": "saus",
    "badge": "Porsi Lauk",
    "tagClass": "tag-gurih",
    "spiceLevel": "Gurih Renyah",
    "price": 35000,
    "soldOut": false,
    "portionTag": "Porsi 2-4x",
    "desc": "Lauk doang bisa untuk 2-4x makan. Potongan ayam fillet crispy gurih lezat dan renyah tahan lama.",
    "image": "assets/images/menu-tepung-oat.jpg"
  },
  {
    "id": "lauk-lada-hitam",
    "name": "Ayam Lada Hitam",
    "category": "saus",
    "badge": "Porsi Lauk",
    "tagClass": "tag-pedas",
    "spiceLevel": "Hangat Pedas",
    "price": 35000,
    "soldOut": false,
    "portionTag": "Porsi 2-4x",
    "desc": "Lauk doang bisa untuk 2-4x makan. Potongan ayam empuk dimasak saus blackpepper pekat dengan sensasi pedas hangat rempah.",
    "image": "assets/images/menu-lada-hitam.jpg"
  },
  {
    "id": "lauk-tahu-tausi",
    "name": "Ayam Tahu Tausi",
    "category": "saus",
    "badge": "Habis",
    "tagClass": "tag-habis",
    "spiceLevel": "Gurih Fermentasi",
    "price": 0,
    "soldOut": true,
    "portionTag": "Porsi 2-4x",
    "desc": "Lauk doang bisa untuk 2-4x makan. Olahan ayam segar dan tahu sutra lembut dengan bumbu tausi kedelai hitam gurih.",
    "image": "assets/images/menu-tahu-tausi.jpg"
  },
  {
    "id": "goreng-bawang-jahe",
    "name": "Ayam Bawang Jahe",
    "category": "goreng",
    "badge": "Habis",
    "tagClass": "tag-habis",
    "spiceLevel": "Sedap Hangat",
    "price": 0,
    "soldOut": true,
    "desc": "Ayam goreng diolah dengan tumisan bumbu irisan bawang dan jahe segar beraroma wangi memikat.",
    "image": "assets/images/menu-bawang-jahe.jpg"
  },
  {
    "id": "goreng-mentega",
    "name": "Ayam Goreng Mentega",
    "category": "goreng",
    "badge": "Habis",
    "tagClass": "tag-habis",
    "spiceLevel": "Manis Gurih",
    "price": 0,
    "soldOut": true,
    "desc": "Ayam goreng dengan karamelisasi saus mentega aromatik dan kecap inggris legit khas oriental.",
    "image": "assets/images/menu-mentega.jpg"
  },
  {
    "id": "goreng-ngohiang",
    "name": "Ayam Goreng Ngohiang",
    "category": "goreng",
    "badge": "Habis",
    "tagClass": "tag-habis",
    "spiceLevel": "Five-Spice Gurih",
    "price": 0,
    "soldOut": true,
    "desc": "Ayam goreng dengan aroma bumbu rempah five-spice (ngohiang) tradisional yang harum meresap.",
    "image": "assets/images/menu-ngohiang.jpg"
  },
  {
    "id": "goreng-kecap",
    "name": "Ayam Goreng Kecap",
    "category": "goreng",
    "badge": "Habis",
    "tagClass": "tag-habis",
    "spiceLevel": "Kecap Manis",
    "price": 0,
    "soldOut": true,
    "desc": "Ayam goreng dimasak kuah kecap manis gurih oriental beraroma bawang bombay sedap.",
    "image": "assets/images/menu-ayam-kecap.jpg"
  },
  {
    "id": "goreng-kering",
    "name": "Ayam Goreng Kering",
    "category": "goreng",
    "badge": "Habis",
    "tagClass": "tag-habis",
    "spiceLevel": "Original Gurih",
    "price": 0,
    "soldOut": true,
    "desc": "Ayam goreng kering bumbu marinasi rempah, berkulit renyah garing dengan daging empuk.",
    "image": "assets/images/menu-goreng-kering.jpg"
  },
  {
    "id": "goreng-masak-pedas",
    "name": "Ayam Masak Pedas",
    "category": "goreng",
    "badge": "Habis",
    "tagClass": "tag-habis",
    "spiceLevel": "Pedas Rica",
    "price": 0,
    "soldOut": true,
    "desc": "Olahan ayam bumbu rica cabai merah pedas mantap khas racikan dapur Mak Sri Kitchen.",
    "image": "assets/images/menu-masak-pedas.jpg"
  },
  {
    "id": "goreng-saos-inggris",
    "name": "Ayam Goreng Saos Inggris Mak Sri",
    "category": "goreng",
    "badge": "Habis",
    "tagClass": "tag-habis",
    "spiceLevel": "Gurih Asam Manis",
    "price": 0,
    "soldOut": true,
    "desc": "Ayam goreng renyah disiram racikan saos inggris spesial Mak Sri Kitchen yang wangi gurih.",
    "image": "assets/images/menu-saos-inggris.jpg"
  },
  {
    "id": "goreng-korea",
    "name": "Ayam Goreng Korea",
    "category": "goreng",
    "badge": "Habis",
    "tagClass": "tag-habis",
    "spiceLevel": "Manis Pedas",
    "price": 0,
    "soldOut": true,
    "desc": "Ayam goreng crispy bersalut saus manis gurih pedas ala Korea dengan taburan biji wijen.",
    "image": "assets/images/menu-ayam-korea.jpg"
  },
  {
    "id": "kulit-original",
    "name": "Kulit Crispy Original",
    "category": "kulit",
    "badge": "Habis",
    "tagClass": "tag-habis",
    "spiceLevel": "Gurih Asin",
    "price": 0,
    "soldOut": true,
    "desc": "Kulit ayam goreng tepung super renyah dan gurih, camilan favorit tanpa kuah.",
    "image": "assets/images/menu-kulit-original.jpg"
  },
  {
    "id": "kulit-saos-keju",
    "name": "Kulit Crispy Saos Keju",
    "category": "kulit",
    "badge": "Habis",
    "tagClass": "tag-habis",
    "spiceLevel": "Keju Creamy",
    "price": 0,
    "soldOut": true,
    "desc": "Kulit ayam goreng renyah disajikan lengkap dengan cocolan saus keju cheddar creamy lumer.",
    "image": "assets/images/menu-kulit-keju.jpg"
  },
  {
    "id": "kulit-telur-asin",
    "name": "Kulit Crispy Telur Asin",
    "category": "kulit",
    "badge": "Habis",
    "tagClass": "tag-habis",
    "spiceLevel": "Salted Egg",
    "price": 0,
    "soldOut": true,
    "desc": "Kulit ayam goreng crispy dibalut racikan saus kuning telur asin (salted egg) gurih wangi.",
    "image": "assets/images/menu-kulit-saltedegg.jpg"
  },
  {
    "id": "nasi-goreng-special",
    "name": "Nasi Goreng Special",
    "category": "nasi-sup",
    "badge": "Best Seller",
    "tagClass": "tag-bestseller",
    "spiceLevel": "Gurih Khas",
    "price": 19000,
    "soldOut": false,
    "portionTag": "Favorit",
    "desc": "Nasi goreng resep kuno oriental khas Mak Sri Kitchen dengan suwiran ayam gurih dan aroma smokey wajan.",
    "image": "assets/images/menu-nasgor-ayam.jpg"
  },
  {
    "id": "nasi-goreng-kriuk",
    "name": "Nasi Goreng Kriuk",
    "category": "nasi-sup",
    "badge": "Habis",
    "tagClass": "tag-habis",
    "spiceLevel": "Gurih Renyah",
    "price": 0,
    "soldOut": true,
    "desc": "Nasi goreng resep kuno spesial dengan topping irisan ayam goreng tepung renyah berlimpah.",
    "image": "assets/images/menu-nasgor-kriuk.jpg"
  },
  {
    "id": "nasi-siram-ayam",
    "name": "Nasi Siram Ayam",
    "category": "nasi-sup",
    "badge": "Habis",
    "tagClass": "tag-habis",
    "spiceLevel": "Lembut Gurih",
    "price": 0,
    "soldOut": true,
    "desc": "Nasi putih hangat disiram kuah kental sayuran segar, telur, dan potongan ayam empuk.",
    "image": "assets/images/menu-nasi-siram.jpg"
  },
  {
    "id": "nasi-ayam-jamur",
    "name": "Nasi Ayam Jamur",
    "category": "nasi-sup",
    "badge": "Habis",
    "tagClass": "tag-habis",
    "spiceLevel": "Manis Gurih",
    "price": 0,
    "soldOut": true,
    "desc": "Nasi putih hangat dengan tumisan daging ayam dan jamur gurih berbumbu saus kecap oriental.",
    "image": "assets/images/menu-nasi-ayam-jamur.jpg"
  },
  {
    "id": "nasi-fuyunghay-ayam",
    "name": "Fu Yung Hay Ayam",
    "category": "nasi-sup",
    "badge": "Habis",
    "tagClass": "tag-habis",
    "spiceLevel": "Asam Manis",
    "price": 0,
    "soldOut": true,
    "desc": "Omelet telur tebal renyah isi cacahan daging ayam dan sayuran, disajikan dengan saos asam manis segar.",
    "image": "assets/images/menu-fuyunghay.jpg"
  },
  {
    "id": "sup-ayam-sosis",
    "name": "Sup Ayam Sosis",
    "category": "nasi-sup",
    "badge": "Habis",
    "tagClass": "tag-habis",
    "spiceLevel": "Gurih Hangat",
    "price": 0,
    "soldOut": true,
    "desc": "Sup kuah kental hangat dengan isian daging ayam empuk, potongan sosis, dan kuah kaldu kaya rasa.",
    "image": "assets/images/menu-sup-sosis.jpg"
  },
  {
    "id": "sup-asparagus-ayam",
    "name": "Sup Asparagus Ayam",
    "category": "nasi-sup",
    "badge": "Habis",
    "tagClass": "tag-habis",
    "spiceLevel": "Lembut Gurih",
    "price": 0,
    "soldOut": true,
    "desc": "Sup kuah kental hangat dengan asparagus lembut, suwiran daging ayam, dan serabut telur gurih.",
    "image": "assets/images/menu-sup-asparagus.jpg"
  },
  {
    "id": "tofu-siram-ayam",
    "name": "Tofu Siram Ayam",
    "category": "nasi-sup",
    "badge": "Habis",
    "tagClass": "tag-habis",
    "spiceLevel": "Gurih Halus",
    "price": 0,
    "soldOut": true,
    "desc": "Egg tofu sutra goreng lembut disiram kuah kental kaya bumbu dengan cacahan daging ayam.",
    "image": "assets/images/menu-tofu-siram.jpg"
  },
  {
    "id": "cah-buncis-ayam",
    "name": "Cah Baby Buncis Ayam",
    "category": "nasi-sup",
    "badge": "Habis",
    "tagClass": "tag-habis",
    "spiceLevel": "Gurih Renyah",
    "price": 0,
    "soldOut": true,
    "desc": "Baby buncis muda segar ditumis renyah kres-kres dengan potongan daging ayam gurih aromatik.",
    "image": "assets/images/menu-buncis-ayam.jpg"
  }
];
